### ISSUE TITLE
Heat map creation

### ISSUE THREAD

**Issue by pulsejet** [radialapps/xunk-calendar#1]
Allow creation of a heat map for different dates by exposing an Input

**Comment by pulsejet** [comment]
Fixed

**Comment by ryczbo** [comment]
Hello!

I'm using your calendar with good effects so far but I can't seem to grab an idea of how does the heatmap object look like. I try to use the same kind of object as in selected date, but that doesn't seem to work - the dates I pick don't show up on a calendar with highlighted color, even though I specified a different color for heatmap in my html. Could you give me a hint of how should the heatmap object look?

Thanks!

**Comment by pulsejet** [comment]
Hi @ryczbo 

You can have a look at the demo code to get an idea of how heatmap works https://github.com/radialapps/xunk-calendar/blob/master/src/app/app.component.ts

I don't claim it to be a very clean API since it was developed for a very particular purpose, but I still think it should be easy enough to work with. To summarise, you need to pass a JSON object with the keys as date in the format of `YYYYMMDD` and the value as a number between 0 and 1 IIRC.
