### ISSUE TITLE
Error: BrowserModule has already been loaded.

### ISSUE THREAD

**Issue by sedajollyannfrancez** [radialapps/xunk-calendar#12]
After npm install and implementation in project, having errors in with:

Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by pulsejet** [comment]
Please check if this is fixed by v1.8.2
