### ISSUE TITLE
problem importing XunkCalendarModule into app.module

### ISSUE THREAD

**Issue by rattanakchea** [radialapps/xunk-calendar#13]
after running `npm install xunk-calendar`, I tried to import XunkCalendarModule into app.module.
But the it cannot find the module. I look at XunkCalendar in node_modules directory. I don't see any typescript module or related CSS for angular specific.
Can you help me with this?

![xun-calendar-install](https://user-images.githubusercontent.com/3496405/44180471-75c06a00-a0b1-11e8-8d24-6119982f8853.PNG)

**Comment by pulsejet** [comment]
Hi!

Your directory structure might not be right. Are other dependencies working properly?

A couple of other notes:
* You need `import { XunkCalendarModule } from 'xunk-calendar'` in app.module; the full path may not work.
* It needs Angular 6, and all peer dependencies should be installed. If I remember right, it refuses to work without the animations dependency though it isn't in peer deps yet.
* You've added it to imports

I've created a minimal demo on stackblitz just to ensure everything is working. You can compare your project imports etc. at https://stackblitz.com/edit/angular-nqygzv

**Comment by rattanakchea** [comment]
Hi, I got it working now. In the code sample, you imported this way:
import { XunkCalendarModule } from '../xunk-calendar/xunk-calendar.module';

I removed `.module` and it is working. Do you use `packagr` for building angular package?

I'm interested in contributing to this project where needed.

**Comment by pulsejet** [comment]
Great! Yes, I'm using packagr (all builds are done by Travis, CD to npm). You're welcome to contribute in any way, but just be aware that I made this project a bit too specific to another project of mine, so the code/conventions etc. may not be the best around (read: horrible). I'll be glad if someone can fix these up :P

**Comment by rattanakchea** [comment]
Yes I see that it is very specific for a particular use case (i.e heatmap, date). I had to make many modifications to meet my project. However, this is one of the simplest Angular calendars I could find around. Kudo to you. How much time did you put in to make to build this for first version?

**Comment by pulsejet** [comment]
Thanks! Yeah, I searched high and low for something like this, but there really wasn't anything that stuck to material design strictly (which was a hard requirement), while still being simple enough. The first version took little over an hour if I remember right, but then it was also pretty bare-bones.
